# Generated by Django 5.0.6 on 2024-07-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('F', 'Following'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
