# Generated by Django 5.0.6 on 2024-07-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_follow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FR', 'Follow Request'), ('FA', 'Follow Accepted')], max_length=2),
        ),
    ]
