# Generated by Django 5.0.6 on 2024-07-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hearing_status',
            field=models.CharField(choices=[('deaf', 'Deaf'), ('hard_of_hearing', 'Hard of Hearing'), ('hearing', 'Hearing'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20),
        ),
    ]
