# Generated by Django 5.1.5 on 2025-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_hearing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_user.jpg', upload_to='profile_pictures/'),
        ),
    ]
