# Generated by Django 4.2.7 on 2025-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FR', 'Follow Request'), ('FA', 'Follow Accepted'), ('F', 'Followed')], max_length=2),
        ),
    ]
